[project]
name = "agent-smith"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.6.0",
    "streamlit>=1.44.1",
    "torch>=2.6.0",
    "transformers>=4.50.3",
]
